#https://scriptingchris.tech/2021/05/16/how-to-setup-a-github-actions-pipeline-for-publishing-your-powershell-module/

name: testing
on:
  pull_request: # Only trigger the workflow if there is a pull request to the main branch
    branches: [ main ]

  workflow_dispatch: # Enables the possibility to trigger the workflow manually

  push:
      tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  BUILD_NUMBER: ${{ vars.BUILD_NUMBER }}

jobs:
  # 1st Job -- Building the module
  build:
    runs-on: windows-latest
    steps:
        # Check out the main branch
      - uses: actions/checkout@master

      - name: OTHER TEST
        id: tag
        shell: pwsh
        run: |
          $PS_Module_Version = ('v{0}' -f (Test-ModuleManifest -Path ".\EguibarIT.psd1").Version)

          $oldModuleVersion = (Test-ModuleManifest -Path ".\EguibarIT.psd1").Version
          $publicFunctions = Get-ChildItem -Path '.\Public\*.ps1'
          $privateFunctions = Get-ChildItem -Path '.\Private\*.ps1'
          $ClassesFunctions = Get-ChildItem -Path '.\Classes\*.ps1'
          $EnumsFunctions = Get-ChildItem -Path '.\Enums\*.ps1'
          $totalFunctions = $publicFunctions.count + $privateFunctions.count + $ClassesFunctions.count + $EnumsFunctions.count
          $ModuleBuildNumber = $oldModuleVersion.Build + 1
          $ModuleVersion = "$($oldModuleVersion.Major).$($totalFunctions).$($ModuleBuildNumber)"
          Update-ModuleManifest -Path ".\EguibarIT.psd1" -ModuleVersion $ModuleVersion

          Write-Output "BUILD_NUMBER=$ModuleVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "OLD_NUMBER=$oldModuleVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Read exported variable
        run: |
          echo "${{ env.BUILD_NUMBER }}"
          echo "${{ env.OLD_NUMBER }}"

  # 2nd Job -- Releasing the module
  release:
    name: Release Module
    needs: build
    runs-on: windows-latest

    steps:
      - name: Read exported variable
        run: |
          $PS_Module_Version = ('v{0}' -f (Test-ModuleManifest -Path ".\EguibarIT.psd1").Version)
          $ModuleVersion = (Test-ModuleManifest -Path ".\EguibarIT.psd1").Version

          Write-Output "BUILD_NUMBER=$ModuleVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Output "VERSION_NUMBER=$PS_Module_Version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: show variable
        run: |
          echo "${{ env.BUILD_NUMBER }}"
          echo "${{ env.VERSION_NUMBER }}"
