#https://scriptingchris.tech/2021/05/16/how-to-setup-a-github-actions-pipeline-for-publishing-your-powershell-module/

name: testing
on:
  pull_request: # Only trigger the workflow if there is a pull request to the main branch
    branches: [ main ]

  workflow_dispatch: # Enables the possibility to trigger the workflow manually

  push:
      tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10


jobs:
  # 1st Job -- Building the module
  build:
    runs-on: ubuntu-latest
    steps:
        # Check out the main branch
      - uses: actions/checkout@master

      - name: Is variable exported?
        run: |
          echo "echo_VERSION=$PS_Module_Version" >> "$Env:GITHUB_ENV"

          echo ${{ env.echo_VERSION }}


      - name: Get tag
        id: tag
        shell: pwsh
        run: |
            $ModuleName = (Get-ChildItem -Path ./Output/).Name
            $PS_Module_Version = ('v{0}' -f (Test-ModuleManifest -Path ".\$($ModuleName).psd1").Version)

            echo "echo_VERSION=$PS_Module_Version" >> "$Env:GITHUB_ENV"
            Add-Content -Path "$env:GITHUB_ENV" -Value "AddContent_VERSION=$PS_Module_Version" -Encoding utf8
            echo "OutFile_VERSION=$PS_Module_Version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
            write-output "WriteOutput_VERSION=$PS_Module_Version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

            echo "Step_Version=$PS_Module_Version" >> $GITHUB_OUTPUT

            echo "echo Version ${{ env.echo_VERSION }}"
            echo "AddContent Version ${{ env.AddContent_VERSION }}"
            echo "OutFile Version ${{ env.OutFile_VERSION }}"
            echo "WriteOutput Version ${{ env.WriteOutput_VERSION }}"

            write-Host ${{ env.echo_VERSION }}

            echo "${{ env.echo_VERSION }}"
            echo "${{ env.AddContent_VERSION }}"
            echo "${{ env.OutFile_VERSION }}"
            echo "${{ env.WriteOutput_VERSION }}"


            echo "echo Version $echo_VERSION"
            echo "AddContent Version $AddContent_VERSION"
            echo "OutFile Version $OutFile_VERSION"
            echo "WriteOutput Version $WriteOutput_VERSION"

            echo "$echo_VERSION"
            echo "$AddContent_VERSION"
            echo "$OutFile_VERSION"
            echo "$WriteOutput_VERSION"

            echo "${{ steps.tag.outputs.Step_Version }}"
