#https://scriptingchris.tech/2021/05/16/how-to-setup-a-github-actions-pipeline-for-publishing-your-powershell-module/

name: Build and Release Module
on:
  pull_request: # Only trigger the workflow if there is a pull request to the main branch
    branches: [ main ]

  workflow_dispatch: # Enables the possibility to trigger the workflow manually

  push:
      tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
env:
  # Setting an environment variable with the value of a configuration variable
  MODULE_VERSION: ${{ vars.MODULE_VERSION }}

jobs:
  # 1st Job -- Building the module
  build:
    runs-on: ubuntu-latest
    steps:
        # Check out the main branch
      - uses: actions/checkout@master

      - name: Get tag
        id: tag
        shell: pwsh
        run: |
            $ModuleName = (Get-ChildItem -Path ./Output/).Name
            $PS_Module_Version = ('v{0}' -f (Test-ModuleManifest -Path ".\$($ModuleName).psd1").Version)
            write-host $PS_Module_Version
            echo "::set-output name=MODULE_VERSION::$PS_Module_Version"
            echo "MODULE_VERSION=$PS_Module_Version"  >> $Env:GITHUB_ENV

            echo "Version ${{ env.MODULE_VERSION }}"
